/* Author: Erik Humphrey
 * Date started: February 22nd, 2017
 * Project title: Module 3 - Assignment - GuessTheNumber
 * Description: Game in which the player must guess a random secret number generated by the computer
 */

/* NOTE:
 * If there is a high score, it adds it to the file rather than replacing the top one.
 * Program might crash if you delete the high score file.
 */

import java.util.concurrent.ThreadLocalRandom;
import java.util.regex.*;
import java.util.Scanner;
import java.io.*;

public class GuessTheNumber {

    static int guess;
    static int guessCount;

    private static File highScores = new File("HighScores.txt");
    static int secretNumber = ThreadLocalRandom.current().nextInt(1, 20 + 1);
    static Scanner userInput = new Scanner(System.in);

    public static void main(String[] args) throws IOException {
        // Writes column headers to blank high score table
        // Readers and writers MUST be declared in separate statements
        if (!highScores.exists()) {
            highScores.createNewFile();
            newHighScoreFile();
        }
        else
        {
            BufferedReader br = new BufferedReader(new FileReader(highScores));
            if (br.readLine() == null) {
                newHighScoreFile();
            }
            br.close();
        }

        guessTime();
        System.out.print("I'm thinking of a number from 1 to 20. ");
    }
    
    /* Create a new file with a formatted table
     * pre: none
     * post: HighScores.txt file created with formatted header in first line */

    // The program only records the top score, but the original intention was to have a formatted table using arrays or something
    static void newHighScoreFile() throws IOException {
        BufferedWriter highScoreAuthor = new BufferedWriter(new FileWriter (highScores));
        highScoreAuthor.write(String.format("%-10s %8s\n", "NAME", "GUESSES"));
        highScoreAuthor.close();
    }
    
    /* Prompt user to guess secret number
     * pre: none
     * post: Message is displayed showing user score and high score, scores are compared, program is terminated */
    
    private static void guessTime() {
        System.out.print("Your guess: ");
        
        // Prompt user for guess but prevent non-integer input
        while (!userInput.hasNextInt()) {
		userInput.next();
        System.out.print("Your guess: ");
		}
        guess = userInput.nextInt();
        
        guessCount++;

        if (guess == secretNumber) {

            System.out.println("A winner is you!");

            try {
                BufferedReader scoreChecker = new BufferedReader(new FileReader(highScores));
                // Skip the first lines (formatted headers)
                scoreChecker.readLine();
                scoreChecker.readLine();
                String entry = scoreChecker.readLine();
                
                while (!entry.isEmpty()) {
                    try {
                        try {
                        	// Use regular expressions to find the first number in the file
                            Matcher regex = Pattern.compile("\\d+").matcher(entry);
                            regex.find();
                            int currentHighScore = Integer.valueOf(regex.group());
                        	
                            // Call a method that checks if the user got it on the first try (for the sake of including overloading)
                            
                        	if (checkScore(guessCount))
                        		System.out.println("Wow! You got it on the first guess!");
                        	else
                        		System.out.println("It took " + guessCount + " guesses. The high score is " + currentHighScore + ".");
                        	
                        	// Call a method with different parameters to check the high score
                        	
                            if (checkScore(guessCount, currentHighScore)) {
                                System.out.println("New high score! Please enter your first name.");
                                writeHighScore();
                                
                            }
                            
                            scoreChecker.close();
                            System.out.println("Thanks for playing!");
                            System.exit(0); // Terminate the program

                        }
                        // If there are no scores found, write a high score entry.
                        catch (IllegalStateException noMatchFound) { writeHighScore(); }

                    }
                    catch (NumberFormatException noWriteAccess){
                        System.out.println("ERROR: High score could not be saved");} // Rare case of no write access
                    entry = scoreChecker.readLine();
                }
                scoreChecker.close();
            }
            catch (IOException noReadAccess) {
                System.out.println(""); // Program might work anyway, but this error implies it is open in another program
                // Might trigger if high score is not broken for some reason
            }

            // promptNewGame();

        }
        else if (guess > secretNumber) {
            System.out.println("Try a lower number.");
            guessTime(); }
        else if (guess < secretNumber) {
            System.out.println("Try a higher number.");
            guessTime(); }
    }

    /* Check if user score is less than high score
     * pre: none
     * post: Returned boolean to method */
    
    public static Boolean checkScore(int userScore, int highScore) {
    	Boolean isHighScore = false;
    	if (userScore < highScore) // A lower score is better in this game (least number of guesses)
    		isHighScore = true;
    	return isHighScore;
    }
    
    /* Check if user score equal to 1
     * pre: none
     * post: Returned boolean to method */
    
    public static Boolean checkScore(int userScore) {
    	Boolean isLucky = false;
    	if (userScore == 1)
    		isLucky = true;
    	return isLucky;
    }
    
    /* Write high score to file
     * pre: none
     * post: Formatted user name input and score outputted to file */
    
    private static void writeHighScore() {
        try {
            // The true boolean in the constructor opens file in append mode so it doesn't start fresh with each write
            BufferedWriter highScoreAuthor = new BufferedWriter(new FileWriter(highScores, true));
            highScoreAuthor.newLine();
            highScoreAuthor.write(String.format("%-10s %8s", userInput.next(), guessCount));;
            highScoreAuthor.close();
        } catch (IOException noWriteAccess) {
            System.out.println("ERROR: High score could not be saved.");
        }
    }
}

    /* Prompt user if they would like to start a new game
     * pre: none
     * post: New game started with new values or program stopped */
    
    // This broke somewhere down the line and stopped generating new numbers or resetting the guess count, so I just removed it.
    // Line 108 and 109 have a similar function to saying "no"
    
  /*  private static void promptNewGame() {
        System.out.println("Would you like to play again? Y/N");
        if (userInput.next().equalsIgnoreCase("y"))
        {
        	guessTime();
            System.out.print("I'm thinking of a number from 1 to 20. ");
        }
        else if (userInput.next().equalsIgnoreCase("n"))
        {
            System.out.println("Thanks for playing!");
            userInput.close();
            System.exit(0); // Terminate the program
        }
    }
} */ 